version: "3.7"

services:
  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - 27017
    networks:
      - nodegoat

  server-render:
    build: apps/server-render
    command: >
      sh -c "until nc -z -w 2 mongo 27017 &&
             echo 'mongo ready' &&
             node artifacts/db-reset.js &&
             npm start; do sleep 2; done"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - nodegoat

networks:
  nodegoat:
    driver: bridge
